### ISSUE TITLE
iOS app crashes on startup

### ISSUE THREAD

**Issue by tswast** [MobileChromeApps/cordova-plugin-chrome-apps-bootstrap#1]
I am having trouble running [this app](https://github.com/bananajuicellc/who-goes-first) on iOS. It crashes on both my device and the simulator.

It looks like the issue may be that it is returning nil mimetype for many resources.

![ios-crash-nil-mimetype](https://cloud.githubusercontent.com/assets/247555/6886604/f21575c8-d607-11e4-9398-defcb216de83.png)

**Comment by tswast** [comment]
I am using the latest released CCA.

    $ cca checkenv 
    cca v0.6.0
    Android Development: SDK configured properly.
    iOS Development: SDK configured properly.

**Comment by agrieve** [comment]
Definitely a bug! Thanks for bringing it up. I've published a fix (v2.0.3) that includes the fix (0140fa1765d)

**Comment by tswast** [comment]
Thanks a bunch. My app successfully runs after running

     $ cca upgrade

in the directory.

**Comment by tswast** [comment]
Strangely the app runs successfully in the simulator but not on my phone. I'll open a second issue with the details.
