### ISSUE TITLE
EXC_BAD_ACCESS in determineMimeType during startup on iPhone 5s

### ISSUE THREAD

**Issue by tswast** [MobileChromeApps/cordova-plugin-chrome-apps-bootstrap#2]
This is a follow-up from issue #1  I am still having trouble running [this app](https://github.com/bananajuicellc/who-goes-first) on iOS. It crashes on my device but not the simulator. Both are running iOS 8.2, so it is strange that they act differently.

![ios-bad-access](https://cloud.githubusercontent.com/assets/247555/6910766/583c8146-d71d-11e4-8b57-7624568c71ab.png)

The EXC_BAD_ACCESS error occurs when the path is /private/var/mobile/Containers/Bundle/Application/795335F1-7DE0-4E31-92B7-D65F52AE7842/Who Goes First.app/www/plugins/org.chromium.bootstrap/chromeappstyles.css

It does not crash and exit. Instead it gets stuck on an empty white screen.

**Comment by agrieve** [comment]
Thanks again for helping out with this! I've just published another fix to the function which should resolve the issue.

**Comment by tswast** [comment]
Thanks so much. Works great after updating the org.chromium.bootstrap plugin to 2.0.4.

**Comment by agrieve** [comment]
Woohoo!!
